name: PSI-SVG Action

on:
  workflow_run:
    workflows: ["Webhook Triggered Workflow"]
    types:
      - completed
  workflow_dispatch:

jobs:
  run-psi-svg:
    runs-on: ubuntu-latest
    env:
      SITE_URL: ${{ vars.SITE_URL }}
      PSI_SVG_OUTPUT_PATH: ${{ vars.PSI_SVG_OUTPUT_PATH }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21

      - name: Run PSI-SVG
        run: |
          npx psi-svg $SITE_URL $PSI_SVG_OUTPUT_PATH --strategy=desktop

      - name: Upload output as artifact
        uses: actions/upload-artifact@v2
        with:
          name: psi-svg-output
          path: ${{ env.PSI_SVG_OUTPUT_PATH }}
